// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfFdESXwWgfDZTRBw0m4ICOkL8G3w8Ak',
    appId: '1:631880267505:web:eac7671930c1b6640edb50',
    messagingSenderId: '631880267505',
    projectId: 'library-7e8ef',
    authDomain: 'library-7e8ef.firebaseapp.com',
    storageBucket: 'library-7e8ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhT8XrP_dgkQb8_wBREYK1pnNZpsrRA3A',
    appId: '1:631880267505:android:edc506e33dc52e8d0edb50',
    messagingSenderId: '631880267505',
    projectId: 'library-7e8ef',
    storageBucket: 'library-7e8ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqhYq7NnfnwFgs32maz2SCivUc-XE1ccM',
    appId: '1:631880267505:ios:51f52c8e67b15ad10edb50',
    messagingSenderId: '631880267505',
    projectId: 'library-7e8ef',
    storageBucket: 'library-7e8ef.firebasestorage.app',
    iosBundleId: 'com.example.porject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqhYq7NnfnwFgs32maz2SCivUc-XE1ccM',
    appId: '1:631880267505:ios:51f52c8e67b15ad10edb50',
    messagingSenderId: '631880267505',
    projectId: 'library-7e8ef',
    storageBucket: 'library-7e8ef.firebasestorage.app',
    iosBundleId: 'com.example.porject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUfFdESXwWgfDZTRBw0m4ICOkL8G3w8Ak',
    appId: '1:631880267505:web:33cfce364139461f0edb50',
    messagingSenderId: '631880267505',
    projectId: 'library-7e8ef',
    authDomain: 'library-7e8ef.firebaseapp.com',
    storageBucket: 'library-7e8ef.firebasestorage.app',
  );
}
